CREATE TABLE IF NOT EXISTS public.users (
  id text PRIMARY KEY,
  username text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  created_at timestamptz NOT NULL
);

CREATE TABLE IF NOT EXISTS public.sessions (
  token text PRIMARY KEY,
  user_id text NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL,
  expires_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_sessions_user
  ON public.sessions (user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires
  ON public.sessions (expires_at);

CREATE TABLE IF NOT EXISTS public.characters (
  id text PRIMARY KEY,
  owner_user_id text NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  sheet_json jsonb NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_characters_owner_updated
  ON public.characters (owner_user_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS public.battles (
  id text PRIMARY KEY,
  state_json jsonb NOT NULL,
  side_a_user_id text NOT NULL REFERENCES public.users(id) ON DELETE RESTRICT,
  side_a_character_id text NOT NULL REFERENCES public.characters(id) ON DELETE RESTRICT,
  side_b_character_id text NOT NULL REFERENCES public.characters(id) ON DELETE RESTRICT,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_battles_owner_updated
  ON public.battles (side_a_user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_battles_side_a_character
  ON public.battles (side_a_character_id);
CREATE INDEX IF NOT EXISTS idx_battles_side_b_character
  ON public.battles (side_b_character_id);

CREATE TABLE IF NOT EXISTS public.battlefields (
  id text PRIMARY KEY,
  owner_user_id text REFERENCES public.users(id) ON DELETE SET NULL,
  is_system boolean NOT NULL DEFAULT false,
  sheet_json jsonb NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_battlefields_owner
  ON public.battlefields (owner_user_id);

-- Audit rows intentionally retain source IDs after a user or character is
-- deleted, so user_id and character_id do not have foreign keys.
CREATE TABLE IF NOT EXISTS public.image_gen_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  character_id text NOT NULL,
  created_at timestamptz NOT NULL,
  ok boolean NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_image_gen_char_time
  ON public.image_gen_events (character_id, created_at);
CREATE INDEX IF NOT EXISTS idx_image_gen_user_time
  ON public.image_gen_events (user_id, created_at);

CREATE TABLE IF NOT EXISTS public.narration_styles (
  id text PRIMARY KEY,
  owner_user_id text REFERENCES public.users(id) ON DELETE SET NULL,
  is_system boolean NOT NULL DEFAULT false,
  sheet_json jsonb NOT NULL,
  created_at timestamptz NOT NULL,
  updated_at timestamptz NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_narration_styles_owner
  ON public.narration_styles (owner_user_id);

-- Observability must survive source entity cleanup, so optional entity IDs are
-- deliberately not constrained by foreign keys.
CREATE TABLE IF NOT EXISTS public.balance_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kind text NOT NULL,
  created_at timestamptz NOT NULL,
  battle_id text,
  character_id text,
  payload_json jsonb NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_balance_events_kind_time
  ON public.balance_events (kind, created_at);
CREATE INDEX IF NOT EXISTS idx_balance_events_battle
  ON public.balance_events (battle_id);

-- The browser uses Supabase only for authentication. Application data remains
-- backend-only until explicit per-table policies are designed.
ALTER TABLE public.kshiai_schema_migrations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.characters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.battles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.battlefields ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.image_gen_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.narration_styles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.balance_events ENABLE ROW LEVEL SECURITY;
