import assert from "node:assert/strict";
import { after, before, describe, it } from "node:test";
import { mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
const directory = mkdtempSync(join(tmpdir(), "kshiai-v3-portrait-"));
process.env.DATABASE_URL = "";
process.env.DATABASE_PATH = join(directory, "test.db");
process.env.AUTH_PROVIDER = "legacy";
process.env.LLM_PROVIDER = "mock";
const { query, closeDatabase } = await import("../db.js");
const { buildRoutes } = await import("../routes.js");
const { MockLlmProvider } = await import("../llm/mock.js");
const { createV3StageTrialCandidate, createV3StageTrialSource } = await import("../fixtures/neva-v3.js");
const { prepareV3TrialCharacter } = await import("../repositories/local-v3-trial-characters.js");
const assets = await import("../repositories/character-assets-v2.js");
const { getAssetGeneration, getCurrentAssetGeneration } = await import("../repositories/asset-generations.js");
const { getSheet } = await import("../repositories/characters.js");
const { CharacterGenerationEnvelopeV3Schema, projectCharacterImageBriefV3 } = await import("@kshiai/shared");
const owner="portrait-owner", id="portrait-character";
const headers={Cookie:"kshiai_session=portrait-session","Content-Type":"application/json","Idempotency-Key":"portrait-first"};
let calls=0;
const app=buildRoutes({llm:new MockLlmProvider(),generateCharacterPortrait:async (...args)=>{
 calls++;assert.ok(args[3]);assert.deepEqual(args[4],projectCharacterImageBriefV3(createV3StageTrialCandidate().definition));
 const live=await getSheet(id);assert.ok(live);
 await query("UPDATE characters SET sheet_json=$2 WHERE id=$1",[id,JSON.stringify({...live,record:{...live.record,wins:(live.record?.wins??0)+1}})]);
 return {url:`/api/media/characters/${id}.${args[3]}.jpg`,previousUrl:null,ok:true,note:"generated"};
}});
before(async()=>{
 const now=new Date().toISOString();
 await query("INSERT INTO users (id,username,password_hash,created_at) VALUES ($1,$1,'unused',$2)",[owner,now]);
 await query("INSERT INTO sessions (token,user_id,created_at,expires_at) VALUES ('portrait-session',$1,$2,'2099-01-01T00:00:00Z')",[owner,now]);
 const attempt=await prepareV3TrialCharacter({characterId:id,ownerUserId:owner,envelope:createV3StageTrialCandidate(),source:createV3StageTrialSource()});
 await assets.activateCharacterAuthoringAttempt({attemptId:attempt.attemptId,ownerUserId:owner,candidateDigest:attempt.candidateDigest??undefined});
});
after(async()=>{await closeDatabase();rmSync(directory,{recursive:true,force:true});});
describe("V3 portrait owner lifecycle",()=>{
 it("generates an immutable V3 revision, keeps definition/profile and replays without provider work",async()=>{
  const original=await getCurrentAssetGeneration("character",id);assert.ok(original);
  const sheet=await getSheet(id);assert.ok(sheet);
  const response=await app.request(`/api/characters/${id}/image`,{method:"POST",headers,body:"{}"});
  assert.equal(response.status,200,await response.clone().text());assert.equal(calls,1);
  const latest=await getCurrentAssetGeneration("character",id);assert.ok(latest);assert.notEqual(latest.generationId,original.generationId);assert.equal(latest.schemaVersion,3);
  const old=CharacterGenerationEnvelopeV3Schema.parse(original.content), next=CharacterGenerationEnvelopeV3Schema.parse(latest.content);
  assert.deepEqual({...next.definition,appearance:old.definition.appearance},old.definition);
  assert.deepEqual(next.publicPresentation,old.publicPresentation);assert.deepEqual(next.disclosurePolicy,old.disclosurePolicy);
  assert.deepEqual((await getAssetGeneration(original.generationId))?.content,original.content);
  const saved=await getSheet(id);assert.ok(saved);assert.deepEqual(saved.record,{...sheet.record,wins:(sheet.record?.wins??0)+1});assert.equal(saved.ownerUserId,sheet.ownerUserId);
  assert.equal((await app.request(`/api/characters/${id}/image`,{method:"POST",headers,body:"{}"})).status,200);assert.equal(calls,1);
  assert.equal((await getCurrentAssetGeneration("character",id))?.generationId,latest.generationId);
  const conflicting=await app.request(`/api/characters/${id}/image`,{method:"POST",headers,body:JSON.stringify({extra:"different lighting"})});
  assert.equal(conflicting.status,409);assert.equal(calls,1);
 });
 it("rejects stale and non-owner activation without moving the pointer, then switches only the portrait",async()=>{
  const current=await getCurrentAssetGeneration("character",id);assert.ok(current);
  const input={characterId:id,ownerUserId:owner,expectedGenerationId:current.generationId,operationId:"second",mediaId:"/api/media/characters/second.jpg",mediaRevisionId:"img-second",sourceDigest:"a".repeat(64)};
  await assert.rejects(assets.activateCharacterPortraitRevision({...input,ownerUserId:"another"}),/OWNER_MISMATCH/);
  const second=await assets.activateCharacterPortraitRevision(input);
  await assert.rejects(assets.activateCharacterPortraitRevision(input),/GENERATION_DRIFT/);
  assert.equal((await getCurrentAssetGeneration("character",id))?.generationId,second.generation.generationId);
  const before=CharacterGenerationEnvelopeV3Schema.parse(second.generation.content);
  const res=await app.request(`/api/characters/${id}/image/toggle`,{method:"POST",headers:{...headers,"Idempotency-Key":"toggle-first"}});
  assert.equal(res.status,200,await res.clone().text());
  const toggled=await getCurrentAssetGeneration("character",id);assert.ok(toggled);
  const candidate=CharacterGenerationEnvelopeV3Schema.parse(toggled.content);
  assert.notEqual(candidate.definition.appearance.portrait?.mediaId,before.definition.appearance.portrait?.mediaId);
  assert.deepEqual({...candidate.definition,appearance:before.definition.appearance},before.definition);
  assert.equal(calls,1);
 });
 it("rejects active authoring and provider failure without appending a generation",async()=>{
  const current=await getCurrentAssetGeneration("character",id);assert.ok(current);
  await query("UPDATE character_asset_states SET active_attempt_id='busy' WHERE character_id=$1",[id]);
  await assert.rejects(assets.activateCharacterPortraitRevision({characterId:id,ownerUserId:owner,expectedGenerationId:current.generationId,operationId:"busy",mediaId:"unused",mediaRevisionId:"unused",sourceDigest:"b".repeat(64)}),/NOT_READY/);
  await query("UPDATE character_asset_states SET active_attempt_id=NULL WHERE character_id=$1",[id]);
  const failing=buildRoutes({llm:new MockLlmProvider(),generateCharacterPortrait:async()=>{throw new Error("test provider failure");}});
  const res=await failing.request(`/api/characters/${id}/image`,{method:"POST",headers:{...headers,"Idempotency-Key":"failing-image"},body:"{}"});
  assert.equal(res.status,502);assert.equal((await getCurrentAssetGeneration("character",id))?.generationId,current.generationId);
 });
});
